project: HomePlanner

ai_policies:
  # Рабочая директория всегда корень репозитория
  working_dir: repo_root

  # Перед выполнением команд необходимо сверяться с документацией
  require_docs:
    - "docs/DEVELOPMENT.md#Тестирование"

  # Запуск тестов (по умолчанию)
  test:
    command: "uv run pytest -vv -r a"
    path: "tests/"
    coverage:
      enabled: true
      command: "uv run pytest --cov=backend --cov-report=html"

  # Ограничения на изменения окружения и зависимостей
  environment_guards:
    forbid_env_changes: true          # запрещает создавать/удалять/менять venv
    forbid_dependency_changes: true   # запрещает устанавливать/удалять/обновлять пакеты
    no_venv_modification: true
    no_pip_install: true
    no_uv_add_or_sync_without_user_approval: true

  # Правила выполнения команд
  command_rules:
    separate_commands: true   # не объединять команды в одну строку
    forbid_cd: true           # не менять рабочую директорию
    default_python_runner: "uv"

  # Git‑политики
  git:
    commit_policy: "manual_only"  # коммиты/пуши только по явной команде пользователя
    shortcuts:
      gc: "!gc"
      gcp: "!gcp"
      gp: "!gp"
      gpr: "!gpr"

  # Дополнительные рекомендации для AI/CI
  notes:
    - "Не объединяйте активацию окружения и запуск тестов в одну строку."
    - "Не используйте флаги запуска сервера, все параметры берутся из config/settings.toml."
    - "При необходимости уточнений — сначала перечитайте docs/DEVELOPMENT.md."


