"""Add groups table

Revision ID: 029e6193a551
Revises: 
Create Date: 2025-11-01 20:30:17.493338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029e6193a551'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create groups table first
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=False)
    
    # Add group_id columns using batch mode for SQLite
    try:
        with op.batch_alter_table('events', schema=None) as batch_op:
            batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
            batch_op.create_index('ix_events_group_id', ['group_id'], unique=False)
            batch_op.create_foreign_key('fk_events_group_id', 'groups', ['group_id'], ['id'])
    except Exception:
        # Column might already exist
        pass
    
    try:
        with op.batch_alter_table('tasks', schema=None) as batch_op:
            batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
            batch_op.create_index('ix_tasks_group_id', ['group_id'], unique=False)
            batch_op.create_foreign_key('fk_tasks_group_id', 'groups', ['group_id'], ['id'])
    except Exception:
        # Column might already exist
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_group_id', type_='foreignkey')
        batch_op.drop_index('ix_tasks_group_id')
        batch_op.drop_column('group_id')
    
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_events_group_id', type_='foreignkey')
        batch_op.drop_index('ix_events_group_id')
        batch_op.drop_column('group_id')
    
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
