"""Add interval task type and interval_days field

Revision ID: 59eedfe7933f
Revises: 029e6193a551
Create Date: 2025-11-01 20:40:36.408529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59eedfe7933f'
down_revision: Union[str, None] = '029e6193a551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_type', sa.Enum('RECURRING', 'INTERVAL', name='tasktype'), nullable=False, server_default='RECURRING'))
        batch_op.add_column(sa.Column('interval_days', sa.Integer(), nullable=True))
        batch_op.alter_column('recurrence_type',
                   existing_type=sa.VARCHAR(length=7),
                   type_=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', 'CUSTOM', 'INTERVAL', name='recurrencetype'),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('recurrence_type',
                   existing_type=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', 'CUSTOM', 'INTERVAL', name='recurrencetype'),
                   type_=sa.VARCHAR(length=7),
                   nullable=False)
        batch_op.drop_column('interval_days')
        batch_op.drop_column('task_type')
    # ### end Alembic commands ###

