"""make_recurrence_interval_nullable

Revision ID: 65b1a7f858d4
Revises: 59eedfe7933f
Create Date: 2025-11-01 21:29:50.948700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b1a7f858d4'
down_revision: Union[str, None] = '59eedfe7933f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('recurrence_interval',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('recurrence_interval',
                   existing_type=sa.INTEGER(),
                   nullable=False)
    # ### end Alembic commands ###

